---
title: "2022_34"
date: "2022-08-23"
format: html
editor: visual
---

TidyTuesday week 34, data from [Summarizing CPU and GPU Design Trends with Product Data](https://arxiv.org/abs/1911.11313)

```{r libraries}
library(tidyverse)
library(ggforce)
library(ggh4x)
library(ggtext)
library(showtext)
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)

data = readr::read_csv('data/chip_dataset.csv') %>% janitor::clean_names()
```

```{r fonts}
font_add_google("Josefin Sans")
f1 = "Josefin Sans"
font_add_google("Open Sans")
f2 = "Open Sans"
```

```{r "plot 1"}
#| warning: false
p1 = data %>% mutate(date=lubridate::ymd(release_date)) %>%
  drop_na(date,freq_m_hz) %>%
  ggplot(aes(date,freq_m_hz)) +
  geom_mark_hull(aes(group=type, fill=type, color=type, label = type),show.legend = FALSE,expand = unit(2.5, "mm"), alpha=.1, con.cap = 0, label.fontsize = 11, label.family = f2, con.size = .4) +
  geom_point(aes(color=type), alpha=.5, size=.7, show.legend = FALSE) +
  scale_y_continuous(limits=c(0,5000), expand=c(0.00,0.00),position="right") +
  scale_x_date(date_breaks = "1 year", date_labels = "'%y", expand=c(0.025,0.025)) +
  scale_color_manual(values=c("#26924A","#803998")) +
  scale_fill_manual(values=c("#26924A","#803998")) +
  coord_cartesian(clip="off") +
  cowplot::theme_minimal_grid(11.5) +
  theme(text=element_text(family=f2),
        panel.grid.major.x = element_blank(),
        axis.ticks.length.x=unit(.25, "cm"),
        axis.title.x=element_text(size=11, margin=margin(t=3)),
        axis.title.y.right=element_text(size=11, margin=margin(l=5)),
        plot.title.position = "plot",
        plot.title=element_markdown(family=f1, size=14.2),
        plot.subtitle=element_text(margin=margin(b=10)),
        plot.caption.position = "plot",
        plot.caption = element_text(color="grey30",hjust=0,margin=margin(t=10)),
        plot.margin=margin(.4,.4,.3,.4,unit="cm")) +
  labs(x="Release date",
       y="Freq (MHz)",
       title="<span style='color:#26924A'>CPUs</span> have higher frequencies, but <span style='color:#803998'>GPUs</span> are catching up.",
       subtitle="Frequency (in MHz) of CPUs and GPUs released from Jan 01, 2000 to Apr 13, 2021",
       caption="TidyTuesday week 34 | Source: Summarizing CPU and GPU Design Trends with Product Data")

ggsave("2022_34.png", p1, height=6, width=8, bg="#fafafa")
```
