---
title: "2023_12"
date: "2023-03-21"
format: html
editor: visual
---

[#TidyTuesday](https://github.com/rfordatascience/tidytuesday) week [12 Programming Languages](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-03-21/readme.md) , data from [Programming Language DataBase](https://pldb.com/index.html).

```{r load libraries}
library(tidyverse)
library(ggtext)
library(showtext)
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```

```{r load font}
font_add_google("Ubuntu Mono")
f2 = "Ubuntu Mono"
```

```{r read in data}
languages <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-21/languages.csv')
```

```{r p1, fig.height=3.5, fig.width=3.5, warning=FALSE, message=FALSE}
bg="#fafafa"
caption= "TidyTuesday week 12  •  Source: Programming Language DataBase"
languages |> 
  mutate(lit=book_count+semantic_scholar) |>
  filter(between(appeared, 1970,2022)) |>
  ggplot(aes(x=appeared, y=lit, color=is_open_source)) +
  geom_point(alpha=.7, size=2) +
  geom_point(data=. %>% filter(lit>=125), shape=21, size=3.5, color="black", show.legend = FALSE) +
  geom_text_repel(data=. %>% filter(lit>125),aes(label=str_wrap(title,15)), size=3.8, lineheight=.8, family=f2) +
  scale_color_manual(values=c("#f35b04","#04724D"),na.value="grey40") +
  cowplot::theme_minimal_grid(13) +
  theme(text=element_text(family=f2),
        legend.position="top",
        axis.title = element_text(size=12),
        axis.ticks = element_blank(),
        plot.title.position="plot",
        plot.caption.position = "plot",
        plot.caption=element_text(hjust=0, margin=margin(t=13)),
        legend.margin = margin(l=-37),
        plot.margin=margin(.5,.5,.5,.5,unit="cm"),
        plot.background=element_rect(fill=bg, color=NA)) +
  labs(x="Year (publicly released and/or announced)", 
       y="Literature count", color="Is open source?",
       title="Programming Languages",
       subtitle="Year of language publicly released and/or announced and literature count (number of\nbooks found at isbndb.com and papers from Semantic Scholar), between 1970 and 2022.\nProgramming languages with 125 literature or more are labelled.",
       caption=caption)

ggsave("export/2023_12_p1.png", height=7, width=7)
```

```{r p2 data}
d1 = languages |> 
  filter(is_open_source==TRUE) |>
  filter(appeared >=1940, appeared<=2022) |>
  mutate(x=appeared %% 10,
         dec=appeared - appeared %% 10,
         y=glue::glue("{dec}'s")) |>
  count(x,y,dec) |>
  arrange(dec) |>
  mutate(col= case_when(dec>=2000~"#f35b04",TRUE~"#04724D"),
         y=glue::glue("<span style='color:{col}'>{y}</span>"),
         y=fct_inorder(y)
         )
```

```{r p2, fig.height=3, fig.width=3.5}
d1 |>
  ggplot(aes(x=x, y=fct_rev(y))) +
  geom_point(data=expand.grid(x = 0:9, y = unique(d1$y)), shape=15, size=10, color=bg) +
  geom_point(data=expand.grid(x = 0:9, y = unique(d1$y)), shape="|", size=4.5, color="grey80") +
  ggtext::geom_richtext(aes(label=n), size=4.7, label.color=bg, family=f2,fill=bg) +
  scale_x_continuous(expand=c(0,0), breaks=seq(0,9,1)) +
  facet_wrap(~fct_rev(y), ncol=1, scales="free_y") +
  coord_cartesian(clip="off") +
  cowplot::theme_minimal_grid() +
  theme(text=element_text(family=f2),
        legend.position="top",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y=element_line(),
        plot.margin=margin(1,1.75,1,1,unit="cm"),
        plot.title.position="plot",
        plot.caption.position = "plot",
        plot.caption=element_text(hjust=0, margin=margin(t=15), size=10, lineheight = 1.1),
        plot.subtitle=element_text(lineheight=1.1, margin=margin(t=3,b=13)),
        axis.ticks = element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_markdown(size=13.5, face="bold",family=f2,margin=margin(r=25)),
        axis.title=element_blank(),
        strip.text=element_blank(),
        plot.background=element_rect(fill=bg, color=NA)) +
  labs(x="Month", y="Decade",title="Open-source Programming Languages",
       subtitle="452 open-source programming languages by publicly released and/or announced year,\nbetween 1968 and 2022",
       caption="TidyTuesday week 12  •  Source: Programming Language DataBase\nPlot inspired by Peter Gorman @barelymaps")

ggsave("export/2023_12_p2.png", height=6, width=8)
```

```{r p3, fig.height=3, fig.width=4}
languages |> filter(is_open_source==TRUE, appeared<=2022) |> 
  mutate(type2= fct_lump(type,1)) |> 
  group_by(appeared) |>
  arrange(appeared, type2, bygroup=TRUE)|>
  mutate(id=row_number()) |>
  ggplot(aes(x=appeared, y=id, color=type2)) +
  geom_point() +
  scale_x_continuous(breaks=seq(1970,2020,10)) +
  scale_color_manual(values=c("#f35b04","#04724D"),na.value="grey40") +
  cowplot::theme_minimal_grid() +
  theme(text=element_text(family=f2),
        legend.position="top",
        legend.title=element_text(size=13),
        legend.text=element_text(size=13),
        plot.title.position="plot",
        plot.caption.position = "plot",
        plot.caption=element_text(hjust=0),
        legend.margin = margin(l=-34),
        plot.margin=margin(.5,.5,.5,.5,unit="cm"),
        plot.background=element_rect(fill=bg, color=NA)) +
  labs(title="Open-source languages",
       subtitle="452 open-source programming languages by publicly released and/or announced year, between\n1960 and 2022.",
       color="PLDB's subjective ontology category:", x="Year", y="Count", caption=caption)

ggsave("export/2023_12_p3.png", height=6, width=8)
```