---
title: "2023_44"
format: html
editor: visual
---

TidyTuesday week 44 [US House Election Results](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-11-07/readme.md), data from [MIT Election Data and Science Lab](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IG0UN2).

```{r load libraries}
library(tidyverse)
library(sf)
library(ggragged)
library(showtext)
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)g
```

```{r load fonts}
font_add_google("Jost")
font_add_google("Staatliches","staat")
```

```{r read in data}
house <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-11-07/house.csv')

m= tigris::congressional_districts(cb=TRUE,year=2021)
```

#### Mountain states (2012-2022)
```{r, message=FALSE}
house1 = house |> filter(year>=2011, year!=2022) |>
  select(year,state:state_ic,district,party,candidatevotes,totalvotes) |>
  mutate(STATEFP=str_pad(state_fips,2,pad="0")) |>
  filter(state_po %in% usmap::.mountain) |>
  group_by(year,state, state_po,STATEFP,district,party,totalvotes) |>
  summarise(val=sum(candidatevotes)) |>
  ungroup() |>
  mutate(pct=val/totalvotes) |>
  group_by(year,state, state_po, district) |>
  slice_max(pct) |>
  ungroup() |>
  mutate(district=case_when(state_po=="MT"~"Congressional District (at Large)",
                            state_po=="WY"~"Congressional District (at Large)",
                            TRUE~district
                            ))

m1 = m |> filter(STATEFP %in% house1$STATEFP) |>
  mutate(district= parse_number(NAMELSAD),
         district=str_pad(district,3,pad="0"),
         district=replace_na(district,"Congressional District (at Large)")) |>
  drop_na(district) |>
  left_join(house1, by=c("STATEFP","district")) |>
  mutate(fac = case_when(year>=2014~"1",TRUE~"2"),
         party=str_to_title(party))
```


```{r plot, fig.height=3.5, fig.width=3.5}
# reference: https://www.nytimes.com/interactive/2016/11/01/upshot/many-ways-to-map-election-results.html
ggplot() +
  geom_sf(data=m1, aes(fill=party, alpha=pct), color="white", linewidth=.1) +
  facet_ragged_rows(vars(corhot= 1+ year %in% c(2014,2018,2020)),
                    vars(as.character(year))) +
  #facet_wrap(~year) +
  scale_alpha_identity() +
  scale_fill_manual(values=c("Democrat"="#004A7F","Republican"="#AA0021")) +
  cowplot::theme_map() +
  theme(text=element_text(family="jost"),
        strip.text.x = element_text(size=12),
        strip.text.y = element_blank(),
        panel.spacing = unit(1.1,"line"),
        plot.title=element_text(family="staat", size=20),
        plot.caption = element_text(hjust=0, color="grey30", size=10, margin=margin(t=15)),
        legend.position = c(.75,.9),
        #legend.spacing.y = unit(.4, 'line'),
        plot.margin=margin(.4,.4,.3,.4,unit="cm")) +
  guides(fill = guide_legend(byrow = TRUE)) +
  labs(title="US House results across Mountain States",
       subtitle="Party majority voted for by congressional district and year, between 2012 and 2020.",
       fill="Party:",
       caption="TidyTuesday week 45 | Data: MIT Election Data and Science Lab (MEDSL)")

ggsave("export/2023_44.png", bg="white")
```

