---
title: "2022_51"
date: "2022-12-20"
format: html
editor: visual
---

[TidyTuesday](https://github.com/rfordatascience/tidytuesday) week 51 [Weather Forecast Accuracy](https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-12-20), data from <https://www.weather.gov/>

Geofacet treemap inspired by [Cédric Scherer](https://twitter.com/cedscherer/status/1379493675684786185)

```{r library}
library(tidyverse)
library(treemapify)
library(showtext)
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```

```{r fonts}
font_add_google("Sora")
f1 = "Sora"
font_add_google("Inter")
f2 = "Inter"
```

```{r data}
weather_forecasts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-12-20/weather_forecasts.csv')
cities <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-12-20/cities.csv')
outlook_meanings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-12-20/outlook_meanings.csv')
```

```{r grid}
grid=geofacet::us_states_territories_grid1 %>% filter(code %in% df1$state)
```

```{r "p1"}
#| warning: false
#| message: false
df1 = weather_forecasts %>% 
  filter(possible_error=="none",high_or_low=="high") %>%
  select(date, high_or_low,forecast_temp,observed_temp,city,state) %>%
  drop_na() %>%
  mutate(grp=case_when(forecast_temp>observed_temp~"Forecast > Observed",
                       forecast_temp<observed_temp~"Forecast < Observed",
                       TRUE~"Forecast = Observed",
                       )) %>%
  group_by(state) %>%
  count(grp) %>%
  mutate(prop=n/sum(n))

df1 %>% 
  ggplot(aes(area=prop, fill=grp, subgroup=state)) +
  geom_treemap(color="#fafafa", start="topleft", layout="scol")+
  scale_fill_manual(name="Proportion:",values=c("#C7948D","#007252","#FFC301")) +
  geofacet::facet_geo(~state,grid=grid) +
  cowplot::theme_map(10) +
  theme(legend.position = c(.5,.965),
        legend.justification = "center",
        legend.title = element_text(size=8.5),
        legend.text = element_text(size=8.5),
        text=element_text(family=f2),
        plot.margin=margin(.5,.5,.3,.5,unit="cm"),
        plot.title=element_text(hjust=.5, family=f1),
        plot.subtitle = element_text(hjust=.5),
        plot.caption=element_text(color="grey30", hjust=.5, size=7)
        ) +
  labs(caption="#TidyTuesday week 51 | Source: USA National Weather Service",
       title="High Temperature Forecast Accuracy by State",
       subtitle="Forecasts and observations from 167 cities from Jan 1, 2021 to May 30, 2022")
ggsave("2022_51_high.png",height=6.4, width=8,bg="#fafafa")
```


```{r "p2"}
#| warning: false
#| message: false
df2 = weather_forecasts %>% 
  filter(possible_error=="none",high_or_low=="high") %>%
  select(date, high_or_low,forecast_temp,observed_temp,city,state) %>%
  drop_na() %>%
  mutate(grp=case_when(forecast_temp>observed_temp+2~"Forecast > Observed + 2°F",
                       forecast_temp<observed_temp-2~"Forecast < Observed - 2°F",
                       TRUE~"Forecast = Observed ± 2°F",
                       )) %>%
  group_by(state) %>%
  count(grp) %>%
  mutate(prop=n/sum(n))

df2 %>% 
  ggplot(aes(area=prop, fill=grp, subgroup=state)) +
  geom_treemap(color="#fafafa", start="topleft", layout="scol")+
  scale_fill_manual(name="Proportion:",values=c("#C7948D","#007252","#FFC301")) +
  geofacet::facet_geo(~state,grid=grid) +
  cowplot::theme_map(10) +
  theme(legend.position = c(.5,.965),
        legend.justification = "center",
        legend.title = element_text(size=8.5),
        legend.text = element_text(size=8.5),
        text=element_text(family=f2),
        plot.margin=margin(.5,.5,.3,.5,unit="cm"),
        plot.title=element_text(hjust=.5, family=f1),
        plot.subtitle = element_text(hjust=.5),
        plot.caption=element_text(color="grey30", hjust=.5, size=7)
        ) +
  labs(caption="#TidyTuesday week 51 | Source: USA National Weather Service",
       title="High Temperature Forecast Accuracy by State",
       subtitle="Forecasts and observations from 167 cities from Jan 1, 2021 to May 30, 2022")

ggsave("2022_51_high2.png",height=6.4, width=8,bg="#fafafa")
```


