---
title: "2022_50"
format: html
editor: visual
---

[TidyTuesday](https://github.com/rfordatascience/tidytuesday) week 50 [Monthly State Retail Sales](https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-12-13), data from [United States Census Bureau's Monthly State Retail Sales](https://www.census.gov/retail/state_retail_sales.html).

```{r libraries}
library(tidyverse)
library(ggtext)
library(showtext)
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```

```{r fonts}
font_add_google("Archivo Narrow")
f1 = "Archivo Narrow"
font_add_google("Inter")
f2 = "Inter"
```

```{r data}
state_retail <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-12-13/state_retail.csv',  col_types = "cciciiccc")
coverage_codes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-12-13/coverage_codes.csv')

```

```{r grid df}
grid= data.frame(
  stringsAsFactors = FALSE,
               row = c(8L,5L,4L,3L,1L,6L,5L,4L,
                       3L,6L,5L,4L,3L,3L,4L,5L,6L,7L,8L,3L,4L,5L,
                       6L,7L,2L,3L,4L,5L,6L,7L,3L,4L,5L,6L,7L,4L,
                       5L,6L,7L,3L,4L,5L,6L,8L,2L,3L,4L,5L,1L,2L,4L),
               col = c(1L,1L,1L,1L,1L,2L,2L,2L,
                       2L,3L,3L,3L,3L,4L,4L,4L,4L,4L,4L,5L,5L,5L,
                       5L,5L,6L,6L,6L,6L,6L,6L,7L,7L,7L,7L,7L,8L,
                       8L,8L,8L,9L,9L,9L,9L,9L,10L,10L,10L,10L,11L,
                       11L,11L),
              code = c("HI","CA","OR","WA","AK",
                       "AZ","UT","NV","ID","NM","CO","WY","MT","ND","SD",
                       "NE","KS","OK","TX","MN","IA","MO","AR","LA",
                       "WI","IL","IN","KY","TN","MS","MI","OH","WV","NC",
                       "AL","PA","VA","SC","GA","NY","NJ","MD","DC",
                       "FL","VT","MA","CT","DE","ME","NH","RI")
) %>%
  mutate(state=state.name[match(code,state.abb)],
         state=case_when(code=="DC"~"District of Columbia", TRUE~state)) 
```

#### August 2022 year-over-year percent change in retail value by subsector, naics 441 to 448

```{r p1, fig.height=3.5, fig.width=3.5}
#| message: false
#| warning: false
state_retail= state_retail %>%
  mutate(change_yoy=parse_number(change_yoy),
         change_yoy=replace_na(change_yoy,0))

state_retail %>% filter(between(naics, 441,448)) %>%
  filter(month==8, year ==2022, state_abbr !="USA") %>% 
  left_join(grid, by=c("state_abbr"="code")) %>%
  ggplot(aes(x=col, y=-row,fill=change_yoy)) +
  #geom_tile(aes(fill=change_yoy)) +
  geom_point(aes(fill=change_yoy),shape=21, size=5.7, color="black", stroke=.3) +
  geom_text(aes(label=state_abbr, color= after_scale(prismatic::best_contrast(fill, y = c("white", "black")))), size=2.8, family=f1) +
  colorspace::scale_fill_continuous_diverging(mid=0, palette="Vik", rev=TRUE, breaks=seq(-20,30,10), labels=scales::percent_format(scale=1)) +
  guides(fill = guide_colorbar(barwidth = unit(13, "lines"),barheight = unit(.4, "lines"))) +
  facet_wrap(~subsector) +
  coord_fixed(clip="off") +
  cowplot::theme_map(12) +
  theme(legend.position="top",
        legend.title=element_blank(),
        legend.text=element_text(family=f2, size=8.3),
        legend.margin = margin(t=4),
        legend.justification = "center",
        text=element_text(family=f1),
        panel.spacing = unit(1.5, "lines"),
        strip.text=element_text(margin=margin(b=10)),
        plot.margin=margin(.5,.5,.3,.5,unit="cm"),
        plot.title.position = "plot",
        plot.title=element_markdown(hjust=.5,family=f2, size=11.35, face="plain"),
        plot.caption.position = "plot",
        plot.caption=element_text(hjust=0,color="grey30", family=f2, size=7.5, margin=margin(t=16))
        ) +
  labs(title="<b>State-level Retail Sales</b>: August 2022 year-over-year percent change in retail sales value",
       caption="#TidyTuesday week 50 | Source: US Census Bureau Monthly State Retails Sales")

ggsave("2022_50.png", height=7, width=7, bg="#fafafa")
```


#### New Jersey, year-over-year percent change by subsector, month and year (Jan 2018 - Aug 2022)

```{r, fig.height=3.5, fig.width=3.5}
state_retail %>% 
  mutate(subsector=fct_inorder(subsector)) %>%
  filter(state_abbr=="NJ",) %>%
  ggplot(aes(y=change_yoy, x=month)) +
  ggshadow::geom_shadowline(aes(color=factor(year)), size=.6, key_glyph=draw_key_rect) +
  scale_x_continuous(breaks=seq(1,12,1), labels=c("J","","M","","M","","J","","S","","N","")) +
  scale_y_continuous(label=scales::percent_format(scale=1), limits=c(-100,NA)) +
  facet_wrap(~str_wrap(subsector,22), scales="free_x", ncol=4) +
  scale_color_manual(values=rev(MetBrewer::met.brewer("Egypt", 4))) +
  coord_cartesian(expand=FALSE) +
  cowplot::theme_minimal_grid(10) +
  theme(legend.position = "top",
        legend.justification = "center",
        panel.spacing = unit(1, "lines"),
        panel.grid.major.x = element_blank(),
        axis.title=element_blank(),
        axis.text=element_text(color="grey20"),
        plot.title.position = "plot",
        plot.title=element_markdown(hjust=.5, size=12.7),
        plot.margin=margin(.5,.5,.3,.5,unit="cm"),
        plot.caption=element_text(color="grey40", margin=margin(t=10)))+
  labs(x="Month", y="Year-over-year change",color="Year:",
       title="**New Jersey**: Year-over-year percent change in retail sales value by subsector",
       caption="#TidyTuesday week 50 | Source: US Census Bureau Monthly State Retails Sales")
```



